#pragma once
#include <execution>
#include <concurrent_vector.h>
#include "./headers/Day1.h" 
#include "./headers/Day2.h"
#include "./headers/Day3.h"
#include "./headers/Day4.h"
#include "./headers/Day5.h"
#include "./headers/Day5b.h"
#include "./headers/Day6.h"
#include "./headers/Day7.h"
#include "./headers/Day8.h"
#include "./headers/Day9.h"
#include "./headers/Day10.h"
#include "./headers/Day11.h" 
#include "./headers/Day12.h"
#include "./headers/Day13.h"
#include "./headers/Day14.h"
#include "./headers/Day15.h"
#include "./headers/Day16.h"
#include "./headers/Day17.h"
#include "./headers/Day18.h"
#include "./headers/Day19.h"
#include "./headers/Day20.h"
#include "./headers/Day21.h" 
#include "./headers/Day22.h"
#include "./headers/Day23.h"
#include "./headers/Day24.h"
#include "./headers/Day25.h"

#include <chrono>
#include <iostream>
#include <vector>